/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package docker.hello.world.example;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
